// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using VirtoCommerce.InventoryModule.Data.Repositories;

namespace VirtoCommerce.InventoryModule.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20000000000000_UpdateInventoryV2")]
    partial class UpdateInventoryV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VirtoCommerce.InventoryModule.Data.Model.FulfillmentCenterEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128);

                    b.Property<string>("City")
                        .HasMaxLength(128);

                    b.Property<string>("CountryCode")
                        .HasMaxLength(64);

                    b.Property<string>("CountryName")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DaytimePhoneNumber")
                        .HasMaxLength(64);

                    b.Property<string>("Description");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<string>("GeoLocation")
                        .HasMaxLength(64);

                    b.Property<string>("Line1")
                        .HasMaxLength(1024);

                    b.Property<string>("Line2")
                        .HasMaxLength(1024);

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Organization")
                        .HasMaxLength(128);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(32);

                    b.Property<string>("RegionId")
                        .HasMaxLength(128);

                    b.Property<string>("RegionName")
                        .HasMaxLength(128);

                    b.Property<string>("StateProvince")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("FulfillmentCenter");
                });

            modelBuilder.Entity("VirtoCommerce.InventoryModule.Data.Model.InventoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128);

                    b.Property<bool>("AllowBackorder");

                    b.Property<bool>("AllowPreorder");

                    b.Property<DateTime?>("BackorderAvailabilityDate");

                    b.Property<decimal>("BackorderQuantity");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FulfillmentCenterId")
                        .IsRequired();

                    b.Property<decimal>("InStockQuantity");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<DateTime?>("PreorderAvailabilityDate");

                    b.Property<decimal>("PreorderQuantity");

                    b.Property<decimal>("ReorderMinQuantity");

                    b.Property<decimal>("ReservedQuantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("FulfillmentCenterId");

                    b.HasIndex("Sku");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("VirtoCommerce.InventoryModule.Data.Model.InventoryEntity", b =>
                {
                    b.HasOne("VirtoCommerce.InventoryModule.Data.Model.FulfillmentCenterEntity", "FulfillmentCenter")
                        .WithMany()
                        .HasForeignKey("FulfillmentCenterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
